Dockerfile
README.md

This includes a basic Dockerfile for building an running AF3 library locally without managing the dependencies for PyTorch, etc.
Base Image: `pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime`
Clones from the `main` branch of `https://github.com/lucidrains/alphafold3-pytorch` until a stable release is made (at which point we can update the source).

Add basic Dockerfile

---

alphafold3_pytorch/alphafold3.py

* Right now, nucleotide and ligand atom weights are set to 5 and 10, respectively.
* This change brings these atom weights in line with what is described in Equation 4 of the AF3 supplement. That is, these respective atom weights of 5 and 10 should be *added* to the default protein atom weight of 1. This would now make the nucleotide and ligand atom weights 6 and 11, respectively.

Make `align_weights` in `alphafold3.py` perfectly match Equation 4 in the AF3 supplement

---

alphafold3_pytorch/alphafold3.py
tests/test_af3.py

* Transposes SVD-produced matrix `V` in `WeightedRigidAlign` to get the correct alignment between `pred_coords` and `true_coords`.
* Unit test for `WeightedRigidAlign` has been updated to ensure the correctness of this change.

Transpose SVD matrix `V` in `WeightedRigidAlign` to get correct alignments

---

alphafold3_pytorch/trainer.py

make backward function under `with self.fabric.no_backward_sync(self.model, enabled = is_accumulating)`.

It is unnecessary to synchronize backward in gradient accumulation step.

---

alphafold3_pytorch/alphafold3.py
tests/test_af3.py

* Also adds a check to see if the rotations returned by `WeightedRigidAlign` are unique (thanks @pytorch3d!)
* Lastly, updates the unit test for `WeightedRigidAlign` to more carefully test the correctness of both `WeightedRigidAlign` and `CentreRandomAugmentation`

Correct application of rotations to coordinates in `WeightedRigidAlign` within `alphafold3.py`

---

alphafold3_pytorch/alphafold3.py
tests/test_af3.py

* Ensures that `ExpressCoordinatesInFrame` perfectly matches Algorithm 29 of the AF3 supplement.
* I've also added a unit test to confirm that `ComputeAlignmentError` returns an average alignment error of less than `1e-3` as a sanity check.

Ensure `ExpressCoordinatesInFrame` perfectly matches Algorithm 29 of the AF3 supplement

---

alphafold3_pytorch/alphafold3.py

This PR has 2 contributions:
**1. Using the rollout coordinates for confidence head**
As supplementary information section 4.1, 
> Several of the heads require predicted coordinates, therefore at training time we do a short rollout of the Diffusion Module from pure noise with 20 steps (Main Article Fig. 2c). No gradients are applied to this mini-rollout.
the predicted coordinates was generate by mini-rollout. On other hand, the denoised coordinates generate by diffusion training step is only one of the denoise step of the predict coordinates.
**2. Apply stop gradient on representations and predict structure.** 
As supplementary information section 4.3.5
> During training, a stop gradient is applied to the single and pair embeddings and predicted structure.

Using the rollout coordinates and stop gradient on representations for confidence head 

---

alphafold3_pytorch/alphafold3.py

Fix the bug about [https://github.com/lucidrains/alphafold3-pytorch/pull/26#discussion_r1621905156](https://github.com/lucidrains/alphafold3-pytorch/pull/26#discussion_r1621905156)

rollout pos should be named denoised_atom_pos

---

alphafold3_pytorch/pdb_dataset_curation.py

* Fixes a context manager bug in `pdb_dataset_curation.py`.
* Sadly, it seems that the [`timeout-decorator`](https://github.com/pnpnpn/timeout-decorator) package does not support context manager usage currently. In which case, I've reverted to the previous way of timing out the `process_structure` function while ensuring it is compatible with Python `multiprocessing` (via `use_signals=False`).

Fix context manager bug in `pdb_dataset_curation.py`

---

alphafold3_pytorch/alphafold3.py

`molecule_atom_indices` should be a global index after processing, making it easier to retrieve the corresponding atom based on the token.
I believe this could be a bug, and the purpose of this PR is to fix it.

[fix bug] make molecule_atom_indices to correct global indices

---

alphafold3_pytorch/data/data_pipeline.py
alphafold3_pytorch/data/mmcif_parsing.py
alphafold3_pytorch/data/mmcif_writing.py
scripts/cluster_pdb_mmcifs.py
scripts/filter_pdb_mmcifs.py

* Refactors mmCIF parsing helper functions to add a new (dummy) data pipeline
* One can use this (dummy) data pipeline to load individual mmCIF files and featurize them in a training-ready manner

Refactor mmCIF parsing helper functions to add a new (dummy) data pipeline

---

README.md
alphafold3_pytorch/common/biomolecule.py
alphafold3_pytorch/data/mmcif_parsing.py
scripts/cluster_pdb_mmcifs.py
scripts/filter_pdb_mmcifs.py
tests/test_data_parsing.py

* Switches to filtering preprocessed assembly mmCIF files
* Fixes various bugs in the filtering criterion functions, including incorrect assembly chain reduction (i.e., down to 20 chains total per complex)
* Optimizes the clustering script's arguments for MMseqs2 (thanks [Milot](https://github.com/milot-mirdita)!)

Filter preprocessed assembly mmCIF files, fix various bugs in the filtering criterion functions, and optimize the clustering script

---

scripts/cluster_pdb_mmcifs.py

* Fixes a crash in cluster_pdb_mmcifs.py that occurs when parsing chains with only ligand residues

Fix a new source of crashes in cluster_pdb_mmcifs.py

---

alphafold3_pytorch/life.py

* Adds standardized (template) SMILES strings for each residue (n.b., had to use `canonical=False` for RDKit to not permute the atom ordering when starting with the mmCIF residue templates and exporting a SMILES string)
* These (template) SMILES strings perfectly match the order (and quantity) of the atoms within each template amino/nucleic acid residue, which will later on allow one to more easily inject real mmCIF residue coordinates into these template `Chem.Mol` objects
* The only thing left to consider if and when switching over to using these template SMILES strings is the atoms/coordinates of these template `Chem.Mol` objects should be masked whenever certain atoms in these residues are not present in an input mmCIF file

Add standardized (template) SMILES strings for each residue

---

alphafold3_pytorch/common/amino_acid_constants.py
alphafold3_pytorch/common/dna_constants.py
alphafold3_pytorch/common/ligand_constants.py
alphafold3_pytorch/common/rna_constants.py
alphafold3_pytorch/life.py
data/test/7a4d-assembly1.cif

* Adds updated template indices for distograms and token center atoms in `life.py`
* Also adds an array to map coordinates stored in `atom47` format to residue type-specific atom indices (i.e., in the correct order for each residue)
* Do double-check that the `first` and `last_atom_idx` make sense to you. I literally (for now) just set the first to `0` and the last to the last (zero-based) index of each residue molecule (i.e., using the number of atoms in each template residue/molecule)
* I also set the distogram and token center atom indices as we previously discussed (Ca atoms for protein residues and C1' atoms for nucleotides, when it comes to token center atoms).

Add updated template indices for distograms and token center atoms in `life.py`

---

alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/common/amino_acid_constants.py
alphafold3_pytorch/common/biomolecule.py
alphafold3_pytorch/common/dna_constants.py
alphafold3_pytorch/common/ligand_constants.py
alphafold3_pytorch/common/rna_constants.py
alphafold3_pytorch/inputs.py
alphafold3_pytorch/life.py
alphafold3_pytorch/utils/model_utils.py
tests/test_input.py

* Adds the new `test_pdbinput_input` unit test that verifies functionality of training and sampling with a single PDB mmCIF file and visualizes the output (sampled) 3D coordinates in place of the input 3D coordinates within the original input mmCIF.
* Also treats modified polymer residues as N-atom ligands following the AF3 supplement.
* **NOTE**: The two `TODO` comments left in `input.py` denote two bugs (I believe) I've identified where padding at the end of a tensor (for ligands I presume) leads to either the wrong residue ID being set for padded tokens or leaves some tokens without any molecule type in `is_molecule_types`. These should be looked at and addressed in separate issues after merging this PR.

Add `test_pdbinput_input` unit test

---

alphafold3_pytorch/data/weighted_pdb_sampler.py
scripts/filter_pdb_mmcifs.py

Addressed the issue related to different chains being clustered together incorrectly. This version will now offset the cluster IDs for each chain mapping, as discussed in #93.
Moreover, I tried to speed up the initialization of WeightedPDBSampler by removing some redundant type checks. It seems that this decorator slows down the parallelization of Polars, and removing all type checks will cut down the time from ~40s initially to around ~9s. In this version, I kept most of the ones added by @amorehead, but I removed the decorator from `get_chain_count()`, as it will always return a tuple of integers (or raise an error). Similarly, I removed it from `calculate_weight()` since we already employ the `@typecheck` for `get_*_weight()` functions. This change shaves off around 15-20s off of the …

Fix cluster ID arrangement for chains

---

alphafold3_pytorch/alphafold3.py

Hi @lucidrains , thank you for your amazing work and continuing effort on recreating AF3 and other models! It's been tremendously helpful for us and the community in general.
While working with the diffusion module from this AF3 implementation, I found some potential issue with the weight rigid align algorithm. I made the following changes.
1. True and pred coordinates are swapped in input in `forward` of `ElucidatedAtomDiffusion`
2. The aligned coordinate output are now a sum of `true_coords_centered` and `true_centroid` in `forward` of `WeightedRigidAlign`
I tested the diffusion module with these changes and can confirm it is now working correctly.

Fixed swapping between true and predicted coordinates in WeightedRigidAlign

---

alphafold3_pytorch/alphafold3.py
tests/test_af3.py

Hi @lucidrains  I found the problem of not passing the test:
In the test code, the augmented input was placed at `pred_coords` position due to previous logic. Now we are aligning true to pred, the augmented input needs to be placed at the `true_coords` position. During training, we also want to align `true_coords` to `pred_coords`. I swapped these two positions in the test code and it passed.
Changes:
1. Swapped true and pred coordinates in input in `forward` of `ElucidatedAtomDiffusion` (Same as last time)
2. Modified `forward` of `WeightedRigidAlign` following steps from this paper: https://igl.ethz.ch/projects/ARAP/svd_rot.pdf. (Same as last time)
3. Moved `random_augment_fn(pred_coords)` from `pred_coords` to `true_coords` location in `test_weighted_rigid_align`. (New)
I'll did some …

WeightedRigidAlign correction

---

alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/inputs.py
tests/test_input.py

* Adds `chains` to all `Input` classes
* Next steps include wiring the `chains` into how we select which val/test metrics to report for which (sampled) chains. In principle, we could just subsample the chain IDs for which we report train/val/test metrics uniformly, since cropping chains then subsampling metrics by the same (cropped) chain IDs should behave the same as not cropping chains then subsampling the metrics.
* In other words, I think we should just tag a small bit of logic in our metric reporting code that filters down the final reported metric values to only those chains that are denoted by `chains`. Also, if `chains` is `None`, I think we should just (like normal) report metric values for all chains in the input structure(s).

Add `chains` to all `Input` classes

---

alphafold3_pytorch/inputs.py
alphafold3_pytorch/utils/data_utils.py

* Revamps modified polymer residue support in `pdb_input_to_molecule_input()`
* Now, modified polymer residues should be "atomized" just like ligand atoms, but for these modified residues, they still retain their original polymer residue (molecule) type (e.g., a modified peptide/protein residue is still treated as a protein residue as far as `is_molecule_types` and `molecule_ids` are concerned)
* Also maybe fixes the flaky `pdb_input` unit test by moving the chain name to index mapping logic to be before the cropping logic
* **N.B.** Also fixes a small bug in assigning RNA and DNA indices into the `is_molecule_types` tensor

Revamp modified polymer residue support in `pdb_input_to_molecule_input()`

---

alphafold3_pytorch/inputs.py
alphafold3_pytorch/utils/data_utils.py

* No longer trying to coerce label atom IDs during training-time bond installation

No longer try to coerce label atom IDs during training-time bond installation

---

alphafold3_pytorch/inputs.py

* Fixes an edge case in determining the indices of atom types for atomized `Chem.Mol` objects

Fix edge case in determining the indices of atom types for atomized `Chem.Mol` objects

---

scripts/cluster_pdb_test_mmcifs.py

* Increases the test set's Tanimoto similarity threshold for ligands, since with `max_ligand_similarity=0.3` no ligands pass all of the test set's redundancy reduction filters.
* Testing this new setting locally.

Increase test set's Tanimoto similarity threshold for ligands

---

alphafold3_pytorch/inputs.py

* RDKit is being silly with its C++-level logs :upside_down_face:

Re-silence RDKit's logs

---

alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/data/mmcif_writing.py
alphafold3_pytorch/inputs.py
alphafold3_pytorch/trainer.py
data/test/209d-assembly1.cif
data/test/721p-assembly1.cif
tests/test_input.py

* Adds the code necessary for running overfitting experiments with the AF3 PDB mmCIF training dataset
* First overfitting experiment is running now locally (on two training dataset mmCIFs: `209d-assembly1` (a hybrid DNA-RNA-ligand complex also with modified amino acid residues) and `721p-assembly1` (a two-chain protein-ligand complex)

Add code necessary for overfitting experiments

---

scripts/cluster_pdb_test_mmcifs.py

* Finalizes the `max_ligand_similarity` argument in the test set's clustering script
* Final (new) test set is now uploaded to the shared OneDrive. That concludes all of our dataset filtering and clustering for training/validation/testing! These splits should be quite robust now.

Finalize `max_ligand_similarity` in test set's clustering script

---

alphafold3_pytorch/common/amino_acid_constants.py
alphafold3_pytorch/inputs.py

* Fixes an `OXT` parsing bug for amino acids
* Adds new subsetting options for the `WeightedPDBSampler`

Fix `OXT` parsing bug for amino acids, and add new subsetting options

---

alphafold3_pytorch/inputs.py

Noticed a potential bug in the alphafold3input to atom input function composition which may be of importance to prediction of arbitrary biomolecular inputs. 
As currently implemented the AlphaFold3Input to Batched Atom Input for the Test Input:
```
alphafold3_input = Alphafold3Input(
proteins = ['MLEICLKLVGCKSKKGLSSSSSCYLEEALQRPVASDF', 'MGKCRGLRTARKLRSHRRDQKWHDKQYKKAHLGTALKANPFGGASHAKGIVLEKVGVEAKQPNSAIRKCVRVQLIKNGKKITAFVPNDGCLNFIEENDEVLVAGFGRKGHAVGDIPGVRFKVVKVANVSLLALYKGKKERPRS'],
ds_dna = ['ACGTT'],
ds_rna = ['GCCAU', 'CCAGU'],
ss_dna = ['GCCTA'],
ss_rna = ['CGCAUA'],
metal_ions = ['Na', 'Na', 'Fe'],
misc_molecule_ids = ['Phospholipid'],
ligands = ['CC1=C(C=C(C=C1)NC(=O)C2=CC=C(C=C2)CN3CCN(CC3)C)NC4=NC=CC(=N4)C5=CN=CC=C5'],
add_atom_ids = True,
add_atompair_ids = True,
directed_bonds = …
```

Potential Bug Fix: AlphaFold3Input_to_Molecule_Lengthed_MolInput  ordering

---

alphafold3_pytorch/life.py

* Makes the `three_atom_indices_for_frame` indices match the polymer residue type-specific atom orderings defined in the corresponding `{amino_acid,rna,dna}_constants.py` files.
* For example, for all amino acids in these `*_constants.py` files, their `N`, `Ca`, and `C` atoms are located at indices 0, 1, and 2.
* To my best knowledge, we rely on these polymer residue type-specific atom orderings in all other places in the code (including `life.py` lower in the file).

Correct the `three_atom_indices_for_frame` indices

---

README.md
alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/common/amino_acid_constants.py
alphafold3_pytorch/common/dna_constants.py
alphafold3_pytorch/common/ligand_constants.py
alphafold3_pytorch/common/rna_constants.py
alphafold3_pytorch/data/data_pipeline.py
alphafold3_pytorch/data/msa_parsing.py
alphafold3_pytorch/inputs.py
alphafold3_pytorch/mocks.py
alphafold3_pytorch/utils/data_utils.py
tests/test_af3.py

* Adds MSA support for all of life's molecules
* Tl;dr is, each MSA file corresponds to one specific polymer chain, and (by way of the clustering script's design) each chain's MSA is of a single molecule type even if the chain contains e.g., some DNA residues mixed with the protein chain's amino acids. In this mixed molecule type scenario, this new MSA parsing code treats these "minority-type" residues in each chain as the corresponding unknown residue type of that molecule's type (e.g., DNA residues in a protein-majority chain are treated as `DN` residues in the final MSA, to give the model some partial additional context about these mixed type chains)
* Ligands and modified polymer residues are simply treated as unknown amino acids (with `restype=20`) in the final MSAs
* **TODO:** For …

Add MSA support for all of life's molecules

---

alphafold3_pytorch/alphafold3.py

* Reverts a recent change to `plddt_labels`, to ensure the construction of the `plddt_mask` follows the following criteria in the AF3 supplement:
```
`l` encompasses **all atoms** and the set of atoms `m ∈ R` is defined as:
• Atoms such that the distance in the ground truth between atom `l` and atom `m` is less than 15 Å if `m` is a protein
atom or less than 30 Å if `m` is a nucleic acid atom.
• Only atoms in polymer chains.
• One atom per token - Cα for standard protein residues and C1′ for standard nucleic acid residues.
```
In other words, the `l` indices in `plddt_mask`'s components need to store a `True` value along this dimension, so indicate that all atoms are considered as source atoms and only a subset of e.g., token center atoms are considered prospective destination atoms

Revert mask creation for `plddt_labels`

---

alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/data/mmcif_writing.py

* Adds support for plotting plDDTs in output mmCIFs for visualization
* Also fixes a bug I introduced where maximum gPDE was used to rank the top sample rather than (as it should be) the minimum gPDE (since this quantity measures the predicted distance error in the generated samples)
* Lastly, simplifies `plddt_mask` creation

Add support for plotting plDDTs in output mmCIFs for visualization

---

alphafold3_pytorch/alphafold3.py

* Corrects the default argument of `diffusion_num_augmentations` from `4` to `48` to match the AF3 paper
* This might have made overfitting a bit easier lol

Correct default argument of `diffusion_num_augmentations`

---

alphafold3_pytorch/inputs.py

* Corrects the values in `molecule_atom_indices` for training-time ligand `PDBInputs` such that ligands and modified polymer residues are now supervised for distogram prediction and all confidence head outputs.
* **NOTE:** This does not correct the inference-time (MoleculeLength ...) input pathways yet. These will need to be corrected accordingly.
* **NOTE:** Currently for (training-time) ligand and modified polymer residue inputs, we simply give them no atom frame indices via `atom_indices_for_frame.append(None)`. This means we'll need to manually construct (k=2) nearest neighbors for each ligand and modified polymer residue token (i.e., atom). Also, for metal ions that are the only atoms in a particular chain, their frames can simply be ignored.

Correct values in `molecule_atom_indices` for training-time ligand `PDBInputs`

---

README.md
alphafold3_pytorch/__init__.py
alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/data/data_pipeline.py
alphafold3_pytorch/data/kalign.py
alphafold3_pytorch/data/template_parsing.py
alphafold3_pytorch/inputs.py
alphafold3_pytorch/life.py
alphafold3_pytorch/mocks.py
alphafold3_pytorch/utils/data_utils.py
alphafold3_pytorch/utils/model_utils.py
tests/configs/alphafold3.yaml
tests/configs/trainer.yaml
tests/configs/trainer_with_atom_dataset.yaml
tests/configs/trainer_with_atom_dataset_created_from_pdb.yaml
tests/configs/trainer_with_pdb_dataset.yaml
tests/configs/trainer_with_pdb_dataset_and_weighted_sampling.yaml
tests/configs/training.yaml
tests/configs/training_with_pdb_dataset.yaml
tests/test_af3.py
tests/test_dataloading.py
tests/test_input.py
tests/test_template_loading.py
tests/test_trainer.py

* Adds support for templates of all of life's molecules (credit to @sj900 for kicking off the development of the template pipeline).
* Adds new atom-wise ligand frames for confidence head outputs. Previously, only one ligand frame was defined for a given ligand molecule (residue). Following the AF3 supplement (since ligands and modified polymer residues are atomized), now these ligand frames are computed uniquely for each atom in a ligand molecule (residue).
* Now leaves template and MSA features unmasked with regards to `is_protein_mask`, as now MSAs and templates can be of any molecule type.
* Updates the `align_error_mask` to allow PAE to be computed for any token that is associated with a valid (i.e., non -1) frame.

Add templates and atom-wise ligand frames for confidence head outputs

---

alphafold3_pytorch/utils/model_utils.py

* Defaults to not attempting to construct frames for chains with less than 3 tokens present

Do not attempt to construct frames for chains less than length 3

---

alphafold3_pytorch/inputs.py

* Fixes an occasional bug caused by modified polymer residues, where unsorted order of `unique_chain_residue_indices` would cause the cropped batch size to exceed e.g., 384

Fix occasional bug caused by modified polymer residues

---

alphafold3_pytorch/alphafold3.py

* Allows one to checkpoint the `ConfidenceHead`'s activations, which is important when increasing `diffusion_num_augs`

Allow one to checkpoint the `ConfidenceHead`'s activations

---

alphafold3_pytorch/inputs.py
alphafold3_pytorch/trainer.py
alphafold3_pytorch/utils/utils.py
pyproject.toml

* Ensures no null `BatchedAtomInputs` are passed to one's Trainer, e.g., to prevent multi-GPU communication syncing deadlocks

Ensure no null `BatchedAtomInputs` are passed to the Trainer

---

Dockerfile

To get the example usage code from the README working, the following libraries needed to be added to the Dockerfile:
```
libxrender1 \
libxtst6 \
libxext6 \
libxi6 \
```

Add libxrender, libxtst6, libxext6, libxi6 for ChemDraw to get example code working

---

alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/attention.py
alphafold3_pytorch/common/amino_acid_constants.py
alphafold3_pytorch/common/biomolecule.py
alphafold3_pytorch/common/dna_constants.py
alphafold3_pytorch/common/ligand_constants.py
alphafold3_pytorch/common/mmcif_metadata.py
alphafold3_pytorch/common/rna_constants.py
alphafold3_pytorch/configs.py
alphafold3_pytorch/data/data_pipeline.py
alphafold3_pytorch/data/kalign.py
alphafold3_pytorch/data/mmcif_parsing.py
alphafold3_pytorch/data/msa_parsing.py
alphafold3_pytorch/data/template_parsing.py
alphafold3_pytorch/data/weighted_pdb_sampler.py
alphafold3_pytorch/inputs.py
alphafold3_pytorch/life.py
alphafold3_pytorch/trainer.py
alphafold3_pytorch/utils/data_utils.py
alphafold3_pytorch/utils/model_utils.py
alphafold3_pytorch/utils/utils.py
pyproject.toml
scripts/cluster_pdb_test_mmcifs.py
scripts/cluster_pdb_train_mmcifs.py
scripts/cluster_pdb_val_mmcifs.py

While trying to update the packages required for the project, I encountered a few errors with NumPy. It seems that the version required by the project (1.23.5) does not compile for later versions of Python (in my case, 3.12.5). This PR bumps the version of NumPy to allow the latest 2.0+ to be used. Although there were quite a few changes in their API, it didn't seem to affect the code in the project (based on the automatic checks performed).
Furthermore, while running the tests on my machine, I could see many other deprecation warnings, so I took the time to fix them. Please let me know if you find anything off!

Update deprecated code

---

alphafold3_pytorch/inputs.py

* Ensures modified and unmodified polymer residues are not "mixed together" during `pdb_input_to_molecule_input` conversions.
* This patch is needed to (consistently) successfully convert `7n2c-assembly1` and `5o7v-assembly1` into `AtomInputs`.

Ensure modified and unmodified polymer residues are not "mixed together"

---

tests/test_dataloading.py
tests/test_msa_loading.py
tests/test_template_loading.py

As @amorehead mentioned in #236, I have used the `sample_only_pdb_ids` flag to sample based only on the mmcifs found in the testing data. I also ported this code over to `pathlib`, to make it a bit more readable.

Specify test IDs for PDB dataset during tests

---

alphafold3_pytorch/inputs.py
alphafold3_pytorch/trainer.py

* Addresses a template feature CPU memory issue for large inputs, which can arise since template features are constructed (for simplicity of implementation) prior to cropping (during training).
* Now, users can specify how many template tokens are allowed in each e.g., training, validation, test example per one's CPU memory limitations.

Address template feature CPU memory issue for large inputs

---

alphafold3_pytorch/inputs.py

* Simply skips template feature creation if inputs are too large, to not throw away examples unnecessarily

Simply skip template feature creation if inputs are too large

---

alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/data/template_parsing.py
alphafold3_pytorch/inputs.py

* By default, avoid randomly truncating MSAs since ordering matters
* Also, transpose template unit vectors to have shape (i, j, 3) instead of (j, i, 3)
* Lastly, pass `mask` into `template_embedder` and `msa_embedder`

Various template and MSA fixes

---

alphafold3_pytorch/plm.py

* Fixes a sneaky bug in `plm.py` whereby the extracted protein (character) sequences would consist of all `X`s, since the original dictionary `restypes_index` expects integer keys (and not single-value `torch.tensors`). Instead, to avoid having to transfer a bunch of times between GPU and CPU memory using `i.item()`, we can instead rely on Python's nice coercion of `torch.tensors` into integers (where possible) when performing array indexing.
* Also cleans up some other code.
* A remaining thought: Don't the pLM weights also need to be skipped when saving and loading the state dict?

Fix a sneaky bug in `plm.py`

---

alphafold3_pytorch/inputs.py

* Fixes a syntax error in `alphafold3_input_to_biomolecule()`

Fix syntax in `alphafold3_input_to_biomolecule()`

---

alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/data/template_parsing.py
alphafold3_pytorch/data/weighted_pdb_sampler.py
alphafold3_pytorch/inputs.py
alphafold3_pytorch/plm.py
tests/test_dataloading.py

* Adds the full constraints set from Chai-1
* Fixes a few discrepancies in how PLM inputs are tokenized
* Adds a stricter training set cutoff date at runtime
* Supports skipping specific PDB IDs now
* Adds a 60 second timeout to `pdb_input_to_molecule_input()`
* Fixes a bug in `molecule_to_atom_input()` that would lead to missing tokens not being properly masked out w.r.t. `distogram_atom_indices`, `molecule_atom_indices`, and `atom_indices_for_frames`

Add full constraints set

---

alphafold3_pytorch/alphafold3.py

* Fixes an edge case with the PLM test, since PLM test (random) inputs are not always "realistic" when `is_molecule_types` and `molecule_ids` do not match each other

Fix PLM test

---

alphafold3_pytorch/alphafold3.py

* Ensures pairwise confidence head outputs are masked correctly, e.g., when `batch_size>1`

Ensure pairwise confidence head outputs are masked correctly

---

alphafold3_pytorch/inputs.py

*  Fixes a variable reference.
* Also, it now looks like `mol_atompair_ids` created in `molecule_lengthed_molecule_input_to_atom_input()` is not updated. It's just set to all zeros after the einx code was commented out.

Fix variable reference

---

alphafold3_pytorch/data/data_pipeline.py

* Caches some variables during MSA featurization

Cache some variables during MSA featurization

---

alphafold3_pytorch/inputs.py

Add missing variable

---

alphafold3_pytorch/alphafold3.py
tests/test_af3.py

rewriting [the logic](https://github.com/PDB-REDO/dssp/blob/trunk/libdssp/src/dssp.cpp#L608-L720) for calculating accessible surface area of residues without `mkdssp`, which i still have trouble installing
[the logic](https://github.com/PDB-REDO/dssp/blob/trunk/libdssp/src/dssp.cpp#L583-L597) for including the atoms for rsa calculation, linking for review
will submit a pull request up to [pydssp](https://github.com/ShintaroMinami/PyDSSP) once and if successfully completed
[relevant issue](https://github.com/ShintaroMinami/PyDSSP/issues/4)

rewriting logic for computing rsa for model selection

---

alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/utils/utils.py

* Updates and restricts numeric workarounds to ROCm GPUs.
* As an aside, how important is it that the [`softmax` operation](https://github.com/lucidrains/alphafold3-pytorch/blob/097cbff6beb1df51a9c3bbc8cf0a2e2043c9cb9d/alphafold3_pytorch/attention.py#L510) be in `torch.float32` precision (e.g., compared to being autocast to `bfloat16`)? I ask because for large (5000+ atom) inputs, float32 precision requires 30GB or more of GPU memory to compute this softmax when using several `diffusion_num_augmentations`.

Restrict numeric workarounds to ROCm GPUs

---

alphafold3_pytorch/alphafold3.py

Line 8 of Algorithm 24 uses a `LinearNoBias` layer following `LayerNorm` to merge pairwise with attention bias representations, as follows
However, the code has the `LinearNoBias` weights also initialized with zeros, meaning both the weights and biases of these modules are initially zero (or null) which leads to these weights receiving no gradients throughout training.

Remove zero initialization of `to_attn_bias` weights, since for these `bias=False`

---

alphafold3_pytorch/attention.py

Attention pair biasing uses a simple linear (no bias) and a sigmoid function to gate the attention output logits, as shown below

Remove zero init and constant biasing for `to_gate`

---

alphafold3_pytorch/alphafold3.py

* Changes the placeholder `expansion_factor` value, since it's `2` everywhere else in the paper and code

Change placeholder `expansion_factor` value

---

alphafold3_pytorch/alphafold3.py

In the paragraph 2 of section 4.3.2 of the AlphaFold3 supplementary materials, the variable $\Phi_i = (a_i, b_i, c_i)$ explicitly refers to the coordinates of the frame atoms, not the rotation matrix as previously implemented.
The prior implementation mistakenly calculated the rotation matrix for the frames based on the atom coordinates and then incorrectly set $\Phi_i$ to this rotation matrix. This led to a misalignment between the expected coordinates and the rotation matrix used during the alignment error computation.
The bug has been fixed by correctly assigning $\Phi_i$ as the coordinates of the frame atoms. Specifically:
- The atom positions for the frame are now gathered and rearranged directly as $\Phi_i$, without first converting them into rotation matrices.
- The alignment error …

Fix pAE-related bugs
