alphafold3_pytorch/__init__.py
alphafold3_pytorch/alphafold3.py
tests/test_readme.py

Implemented Relative Position Encoding (Algorithm 3). Tested that it runs with no error and shapes match. Further testing may be needed to check for correctness.

Relative Position Encoding (Algorithm 3)

---

alphafold3_pytorch/alphafold3.py
tests/test_af3.py

Implemented SmoothLDDTLoss (Algorithm 27).

Implemented SmoothLDDTLoss

---

tests/test_af3.py

* Adds a new `assert` to evaluate the new `test_atom_ref_pos_to_atompair_inputs()` test in `test_af3.py`

Add assert to new test in `test_af3.py`

---

alphafold3_pytorch/attention.py

* Fixes a small syntax typo in `attention.py`

Fix syntax typo in `attention.py`

---

alphafold3_pytorch/pdb_dataset_curation.py
pyproject.toml

* Adds a timeout decorator to pdb_dataset_curation.py

Add timeout decorator to pdb_dataset_curation.py

---

alphafold3_pytorch/pdb_dataset_curation.py

* Fixes the functionality of the `argparse` arguments in `pdb_dataset_curation.py`
* Also fixes some typechecking issues in the script

Fix functionality of argparse arguments in pdb_dataset_curation.py

---

pyproject.toml

* Specifies a required RDKit version range in pyproject.toml

Specify RDKit version in pyproject.toml

---

alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/trainer.py
pyproject.toml

hey, Phil, this PR has 2 contributions:
1. collate_af3_inputs function should return an instence of BatchedAtomInput.
2. use logger to log infermation.

[fix] collate_af3_inputs function should return an instence of BatchedAtomInput

---

scripts/cluster_pdb_mmcifs.py

* Finishes the new implementation of `cluster_pdb_mmcifs.py`
* Will be tested fully (locally) once PDB dataset filtering is complete (locally)

Finish new version of `cluster_pdb_mmcifs.py`

---

README.md
scripts/cluster_pdb_mmcifs.py

* Adds a bug fix for the new PDB clustering script to now group same CCD code-ligands in the same chain together
* Also updates the README.md for the new PDB clustering script

Add bug fix and update `README.md` for new PDB clustering script

---

alphafold3_pytorch/common/biomolecule.py
alphafold3_pytorch/data/errors.py
alphafold3_pytorch/data/mmcif_parsing.py
scripts/filter_pdb_mmcifs.py
tests/test_data_parsing.py

* Corrects two bugs affecting filtered mmCIF files

Correct two bugs affecting filtered mmCIF files

---

alphafold3_pytorch/alphafold3.py
tests/test_af3.py

Following Alg. 30, the alignment error should be a pairwise error.

The alignment error should be a pairwise error.

---

scripts/cluster_pdb_mmcifs.py

* Handles a few edge cases in `cluster_pdb_mmcifs.py`

Handle a few edge cases in `cluster_pdb_mmcifs.py`

---

scripts/cluster_pdb_mmcifs.py

* Speeds up `cluster_pdb_mmcifs.py`

Speed up `cluster_pdb_mmcifs.py`

---

scripts/cluster_pdb_mmcifs.py

* Changes the default number of workers used in `cluster_pdb_mmcifs.py`

Change default number of workers used in `cluster_pdb_mmcifs.py`

---

scripts/cluster_pdb_mmcifs.py

* Switch from using `clustalo` to `mmseqs` for `cluster_pdb_mmcifs.py`

Switch from using `clustalo` to using `mmseqs` for `cluster_pdb_mmcifs.py`

---

scripts/cluster_pdb_mmcifs.py

* Completes the new (faster) PDB dataset clustering implementation
* Tests fine locally (~2 hour runtime in total with `no_workers=16`!)

Finish new (faster) PDB dataset clustering implementation

---

alphafold3_pytorch/data/mmcif_parsing.py
scripts/filter_pdb_mmcifs.py

* Adds date range arguments to `filter_pdb_mmcifs.py` to prepare for evaluation and testing dataset curation

Add date range arguments to `filter_pdb_mmcifs.py`

---

alphafold3_pytorch/common/biomolecule.py
alphafold3_pytorch/data/data_pipeline.py
alphafold3_pytorch/data/mmcif_parsing.py
alphafold3_pytorch/data/mmcif_writing.py
alphafold3_pytorch/utils/data_utils.py

* Adds a new biological assembly expansion function for `Biomolecule` objects

Add manual biological assembly expansion function for `Biomolecule` objects

---

README.md

* Defaults to downloading the PDB from its `20240101` AWS snapshot

Default to downloading the PDB from its `20240101` AWS snapshot

---

alphafold3_pytorch/common/biomolecule.py
alphafold3_pytorch/data/data_pipeline.py

* Adds the parsing steps described in the second paragraph of the AF3 supplement, Section 2.1

Add parsing steps described in second paragraph of AF3 supplement Section 2.1

---

alphafold3_pytorch/common/biomolecule.py
alphafold3_pytorch/data/mmcif_parsing.py
scripts/filter_pdb_mmcifs.py

* Generalizes `CovalentBond` to `Bond` to prepare for bond featurization during model training
* Now manually reconstructing the `_struct_conn.` table in output mmCIF files (e.g., following mmCIF filtering)

Generalize `CovalentBond` to `Bond` to prepare for bond featurization during model training

---

alphafold3_pytorch/__init__.py
alphafold3_pytorch/data/data_pipeline.py
alphafold3_pytorch/data/mmcif_writing.py
alphafold3_pytorch/inputs.py
alphafold3_pytorch/trainer.py
data/test/7a4d-assembly1.cif
tests/test_input.py

* Takes a step towards loading, training, and sampling with mmCIF files
* The `TODOs` left in this PR denote some adjustments that need to be made to `Alphafold3Input` to fully support generic PDB mmCIF file inputs
* Feel free to discuss more in the Discord channel as needed

Take a step towards loading, training, and sampling with mmCIF files

---

scripts/cluster_pdb_mmcifs.py

* Fixes a return type in `cluster_pdb_mmcifs.py`

Fix return type in `cluster_pdb_mmcifs.py`

---

alphafold3_pytorch/inputs.py

* Adds a small fix to `inputs.py`, so that metal ions are not double-counted as a ligand and ion in `is_molecule_types`.
* Also makes sure bonds that couldn't be mapped from mmCIF metadata are skipped to prevent a subsequent crash from unknown variable references.

Add small fix to `inputs.py`

---

alphafold3_pytorch/inputs.py
tests/test_input.py

* Makes training detection more robust for mmCIF bond insertion
* Also cleans up some code along the way

Make training detection more robust for mmCIF bond insertion

---

alphafold3_pytorch/inputs.py

* Avoids using mmCIF training bond inputs if homomeric (e.g., bonded ligand) symmetry is mismatched
* Essentially, e.g., if a bonded ligand exists for only one copy of two identical protein chains, then symmetry is "mismatched" and therefore we do not provide polymer-ligand and ligand-ligand mmCIf bond inputs to the model during training. In such a case, the model is then tasked with inferring these e.g., ligand bonds itself

Do not use mmCIF training bond inputs if symmetry is mismatched

---

alphafold3_pytorch/common/biomolecule.py

* Adds support for filtering down to multiple chains during `Biomolecule` object creation.
* This will be useful for interface (chain ID-based) filtering within `Biomolecule` objects.

Add support for filtering down to multiple chains during `Biomolecule` object creation

---

alphafold3_pytorch/data/weighted_pdb_sampler.py

* Corrects the interface chain IDs curated in `weighted_pdb_sampler.py`, as suggested by @vandrw.

Correct interface chain IDs curated in `weighted_pdb_sampler.py`

---

alphafold3_pytorch/common/biomolecule.py
alphafold3_pytorch/data/data_pipeline.py

* Creates an outline of how to do cropping with `Biomolecule` objects
* NOTE: The `data_pipeline.py` example can be used to visualize the cropped `Biomolecule` PDB complexes as "reconstructed" mmCIF files. Pro tip: Use `Protein Viewer` in VS Code to conveniently visualize most kinds of 3D biomolecule structure files (e.g., `.pdb`, `.mmcif`, `.sdf`) directly in a code editor.

Create outline of how to do cropping with `Biomolecule` objects

---

alphafold3_pytorch/common/biomolecule.py
alphafold3_pytorch/data/data_pipeline.py

* Adds (random) contiguous sequence cropping for `Biomolecule` objects
* Also adds an outline of how weighting should be applied when selecting a cropping function to use during training

Add (random) contiguous sequence cropping for `Biomolecule` objects

---

alphafold3_pytorch/common/biomolecule.py
alphafold3_pytorch/data/data_pipeline.py

* Adds the spatial and spatial interface cropping functions for `Biomolecules` following the AF3 supplement

Add spatial and spatial interface cropping functions for `Biomolecules`

---

alphafold3_pytorch/__init__.py
alphafold3_pytorch/confidence.py
tests/test_af3.py

- Confidence measures and sample ranking
- alignment-based confidence measures (see Section 5.9.1).
- clash penalty in ranking (see Section 5.9.2).
- sample ranking (see Section 5.9.3).

confidence measures and sample ranking

---

README.md
alphafold3_pytorch/inputs.py
tests/test_dataloading.py

* Integrates the `WeightedPDBSampler` within the `PDBDataset`
* Credit to @sj900

Integrate `WeightedPDBSampler` within `PDBDataset`

---

scripts/cluster_pdb_test_mmcifs.py
scripts/cluster_pdb_train_mmcifs.py
scripts/cluster_pdb_val_mmcifs.py
scripts/filter_pdb_test_mmcifs.py

* Creates a more faithful version of validation set's clustering logic (n.b., currently running locally, will upload new validation set clustering outputs to the shared OneDrive once finalized).
* Adds filtering and clustering scripts for the test set, which should be even more stringent and rigorous than AF3's original test set (n.b., will run these locally and upload outputs to OneDrive once finalized).

Create more faithful version of val set, and add test set

---

alphafold3_pytorch/alphafold3.py

* Fixes a missing import in `alphafold3.py`

Fix missing import in `alphafold3.py`

---

alphafold3_pytorch/common/biomolecule.py
scripts/cluster_pdb_test_mmcifs.py
scripts/cluster_pdb_train_mmcifs.py
scripts/cluster_pdb_val_mmcifs.py
scripts/filter_pdb_test_mmcifs.py
scripts/filter_pdb_train_mmcifs.py
scripts/filter_pdb_val_mmcifs.py

* Cleans up and revises the PDB filtering/clustering scripts.
* Now, the validation and evaluation datasets' clustering scripts should be even more stringently designed than before, allowing only novel polymers into each dataset's chains/interfaces for sampling/model evaluation.

Clean up and revise the PDB filtering/clustering scripts

---

alphafold3_pytorch/common/biomolecule.py
alphafold3_pytorch/data/weighted_pdb_sampler.py
alphafold3_pytorch/inputs.py

* Adds various input fixes and enhancements
* Preparing for refactoring of the `pdb_input_to_molecule_input` function

Add various input fixes and enhancements

---

alphafold3_pytorch/common/biomolecule.py
scripts/filter_pdb_val_mmcifs.py

* (Now) defaulting to atomizing ligand and modified polymer residues for `Biomolecules`

Default to atomizing ligand and modified polymer residues for `Biomolecules`

---

scripts/cluster_pdb_train_mmcifs.py

* Fixes a small bug in the AF3 PDB training dataset's clustering script

Fix small bug in train clustering script

---

scripts/cluster_pdb_val_mmcifs.py

* Fixes the Polars filtering syntax used in the validation dataset's clustering script

Fix polars syntax in val clustering script

---

alphafold3_pytorch/alphafold3.py
tests/test_af3.py

compute unresolved protein rasa

unresolved_protein_rasa

---

alphafold3_pytorch/common/amino_acid_constants.py
alphafold3_pytorch/common/dna_constants.py
alphafold3_pytorch/common/rna_constants.py
alphafold3_pytorch/inputs.py
alphafold3_pytorch/utils/data_utils.py
tests/test_af3.py

* Adds various bug fixes and optimizations for `pdb_input_to_molecule_input()`
* Also sets `DEFAULT_NUM_MOLECULE_MODS` to `4` to represent `mod_protein`, `mod_rna`, `mod_dna`, and `mod_unk`. Thoughts?
* Also, not sure why all the tests are failing. Is there something wrong with GitHub Actions here?

Add various bug fixes and optimizations for `pdb_input_to_molecule_input()`

---

alphafold3_pytorch/inputs.py

* Tries to block RDKit logs more robustly

Try to block RDKit logs more robustly

---

alphafold3_pytorch/inputs.py
alphafold3_pytorch/mocks.py

* Fixes a `PDBInput` dataloading case where individual chains are sampled

Fix case where individual chains are sampled

---

alphafold3_pytorch/inputs.py

* Fixes a small `missing_atom_mask` collation bug that occurs when collating e.g., one provided and one `None` `missing_atom_mask` tensor corresponding to two intra-batch `AtomInputs`.
* tl;dr is, for `PDBInputs`, one needs to always pass a `missing_atom_mask`, even if it is composed of all `False` values.

Fix `missing_atom_mask` collation bug

---

alphafold3_pytorch/inputs.py

* Catches RDKit sanitization errors

Catch RDKit sanitization errors

---

alphafold3_pytorch/common/biomolecule.py
alphafold3_pytorch/inputs.py

* Fixes various edge case bugs raised during training-time cropping

Fix various edge case bugs raised during training-time cropping

---

alphafold3_pytorch/alphafold3.py
tests/test_input.py

* Adds proper batching support for masking out missing sampled atom positions

Add proper batching support for masking out missing sampled atom positions

---

alphafold3_pytorch/data/mmcif_writing.py

* Makes the typing more pretty

Make typing more pretty

---

README.md
alphafold3_pytorch/inputs.py

* Improves automatic bond detection for arbitrary PDB ligands or modified polymer residue inputs
* Credit to @ptosco for proposing the `PDB neutral stable molecule` hypothesis!

Improve automatic bond detection for arbitrary PDB ligands or modified polymer residue inputs

---

alphafold3_pytorch/data/weighted_pdb_sampler.py
alphafold3_pytorch/inputs.py
scripts/filter_pdb_test_mmcifs.py
scripts/filter_pdb_train_mmcifs.py

* Fixes batching of `missing_atom_mask` objects by treating padding atoms as missing.
* Also cleans up and optimizes the runtime of other code (useful for overfitting).

Fix batching of `missing_atom_mask`s, and clean up code

---

alphafold3_pytorch/data/data_pipeline.py
alphafold3_pytorch/data/msa_parsing.py
alphafold3_pytorch/inputs.py

* Adds a few MSA bug fixes that arose when testing dataloading for more than one example

Add MSA dataloading bug fixes

---

README.md

* Updates the appreciation section in README.md

Update appreciation in README.md

---

alphafold3_pytorch/common/biomolecule.py
alphafold3_pytorch/data/data_pipeline.py
alphafold3_pytorch/inputs.py
alphafold3_pytorch/utils/data_utils.py

* Crops MSA features during training, to avoid feature shape mismatch errors for large training examples that must be cropped

Crop MSA features during training

---

alphafold3_pytorch/inputs.py

* Handles an edge case when constructing ligand frames

Handle an edge case for ligand frames

---

alphafold3_pytorch/inputs.py

* Fixes an increasing index bug for `PDBInputs`

Fix increasing index bug for `PDBInputs`

---

alphafold3_pytorch/alphafold3.py

* Adds support for mixed precision throughout the model architecture

Support mixed precision throughout architecture

---

alphafold3_pytorch/inputs.py
alphafold3_pytorch/tensor_typing.py

* Makes the ascending indices check batch-aware

Make check batch-aware

---

alphafold3_pytorch/inputs.py

* Makes atom input conversion functions exception-robust

Make atom input conversion functions exception-robust

---

alphafold3_pytorch/alphafold3.py
tests/test_af3.py

* Enables `DistogramHead` checkpointing

Enable `DistogramHead` checkpointing

---

alphafold3_pytorch/alphafold3.py

* Fixes the unpacking of checkpointed inputs for the `DistogramHead`

Fix unpacking of checkpointed inputs

---

README.md
alphafold3_pytorch/common/amino_acid_constants.py
alphafold3_pytorch/common/dna_constants.py
alphafold3_pytorch/common/rna_constants.py

* Addresses https://github.com/lucidrains/alphafold3-pytorch/issues/209

Address non-standard atoms parsing for polymer residues

---

alphafold3_pytorch/alphafold3.py

* Enables one to debug individual input files during `model.forward()`

Enable one to debug individual input files during `model.forward()`

---

alphafold3_pytorch/alphafold3.py

* Fixes a prediction chain ID selection bug in `MultiChainPermutationAlignment`

Fix prediction chain ID selection bug in `MultiChainPermutationAlignment`

---

alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/trainer.py

* Fixes a tensor sharding issue for DeepSpeed
* Yeah, I know...such a pedantic change makes a difference here

Fix tensor sharding issue for DeepSpeed

---

alphafold3_pytorch/inputs.py

* Makes MSA loading fault-tolerant

Make MSA loading fault-tolerant

---

alphafold3_pytorch/inputs.py

* Avoids unnecessary input errors during dataloading

Avoid unnecessary input errors

---

alphafold3_pytorch/inputs.py

* Allows bond order inference to be skipped for input atomized molecules

Allow bond order inference to be skipped for input atomized molecules

---

alphafold3_pytorch/cli.py
alphafold3_pytorch/common/amino_acid_constants.py
alphafold3_pytorch/common/dna_constants.py
alphafold3_pytorch/common/rna_constants.py
alphafold3_pytorch/inputs.py

* Handles an edge case for unknown polymer residues during `pdb_input_to_molecule_input` execution.

Handle edge case for unknown polymer residues

---

alphafold3_pytorch/__init__.py
alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/data/template_parsing.py
alphafold3_pytorch/utils/model_utils.py
tests/test_af3.py

* Makes template unit vector computations match those of OpenFold
* Now, template unit vectors actually have a norm of 1 :rocket:

Make template unit vector computations match those of OpenFold

---

README.md
tests/test_dataloading.py
tests/test_msa_loading.py
tests/test_template_loading.py

I corrected a mistake in the naming of the target folder used by @amorehead in some of the tests. Furthermore, I increased the max number of retry attempts to make sure that the tests find a sample. There is still a chance that it won't find one, in which case the test will fail. Should this be an even higher number?
Finally, I also modified the README a bit to indicate that I only worked on the distogram issue 😄

Fix path issues during testing

---

alphafold3_pytorch/data/data_pipeline.py

* Upgrades the version of `kalign` used for template feature construction

Upgrade version of `kalign`

---

alphafold3_pytorch/inputs.py

* Adds MSA token length filtering

Add MSA token length filtering

---

alphafold3_pytorch/alphafold3.py

* Removes a now-unused variable

Remove now-unused variable

---

alphafold3_pytorch/app.py

This version of the app tries to follow the capabilities of the AlphaFold Server interface, and implements a basic interface to gather various molecules that a user provides. I have not looked at the model inputs too carefully, so it is very possible that the `fold` function will not work well with a checkpoint at the moment. Furthermore, I was not sure how to obtain the predicted aligned error (PAE) plot, nor the plDDT, pTM, or ipTM values, so I left these for a future commit.
Regarding the input for the model, I am currently taking as input proteins, nucleic acids, ligands and metal ions. I have followed the AlphaFold inputs, and checked with the values found in `life.py`, but it might be possible I have missed something. Please let me know if something catches your eye!
I have also …

Add Gradio interface for AlphaFold protein structure predictions

---

alphafold3_pytorch/data/msa_parsing.py

* Fixes the MSA types for dataloading

Fix MSA types

---

alphafold3_pytorch/inputs.py

* Makes MSA pairing fault-tolerant

Make MSA pairing fault-tolerant

---

alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/inputs.py
pyproject.toml
tests/test_af3.py

* Adds new embeddings such as pLM features

Add new embeddings

---

alphafold3_pytorch/alphafold3.py

* Fixes a variable name for runtime

Fix variable name

---

alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/tensor_typing.py
alphafold3_pytorch/utils/model_utils.py

* Fixes a circular import, a missing import, and a leftover code block

Fix a circular import, a missing import, and a leftover code block

---

alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/inputs.py

* Ensures the template embedder and resolved logits always contribute to the loss, to avoid distributed gradient syncing errors

Ensure template embedder and resolved logits always contribute to the loss

---

alphafold3_pytorch/inputs.py

* Fixes a bug in the construction of atom indices à la `PDBInput` that could cause two (or more) separate ligands to be accidentally grouped together if they share the same residue index but not the same chain index, leading to e.g., distogram atom indices being out-of-bounds for the total number of atoms in a complex.
* N.b., for what it's worth, this was one of the trickiest bugs to identify to date. On AMD cards, all you'd get is a generic `HIPError` to go debug, with no reference to an out-of-index error in the e.g., distogram modeling code. On NVIDIA cards, you'd actually get the expected out-of-index error to trigger further debugging.

Fix bug in construction of atom indices à la `PDBInput`

---

alphafold3_pytorch/data/weighted_pdb_sampler.py

See https://github.com/lucidrains/alphafold3-pytorch/issues/265

Python 3.9 compatibility

---

alphafold3_pytorch/data/data_pipeline.py
alphafold3_pytorch/data/msa_parsing.py
alphafold3_pytorch/inputs.py

* Finalizes full MSA pairing support

Add full MSA pairing support

---

alphafold3_pytorch/inputs.py
pyproject.toml

* Adds a missing dependency for downloading distillation data

Add missing dependency

---

alphafold3_pytorch/alphafold3.py

* Fixes some `Alphafold3` module argument types

Fix `Alphafold3` module argument types

---

alphafold3_pytorch/alphafold3.py

* Fixes the name of a variable

Fix name of variable

---

alphafold3_pytorch/inputs.py

* Fixes a typechecking annotation

Fix typechecking annotation

---

alphafold3_pytorch/inputs.py

* Fixes two `verbose` route oversights

Fix two `verbose` route oversights

---

alphafold3_pytorch/inputs.py

* Handles a distillation training edge case

Handle a distillation training edge case

---

README.md
alphafold3_pytorch/alphafold3.py
alphafold3_pytorch/attention.py
pyproject.toml
tests/test_af3.py

https://arxiv.org/abs/2410.17897

value residual learning
